# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudexec < Formula
  desc ""
  homepage "https://github.com/crytic/cloudexec"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-darwin-arm64.tar.gz"
      sha256 "3ec9bc5be84401a813f7eb6a0ae8c517b0320d1d1f01860065f69292148cda35"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-darwin-amd64.tar.gz"
      sha256 "5dba6ea1c7cc60ee9afef85bc532d87a9f03a79655f40104639445c4a2ef201d"

      def install
        bin.install "cloudexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-linux-arm64.tar.gz"
      sha256 "a78059a930f35255603938deab7f1fbec75fc25f0f602babb6d4800818443b1d"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-linux-amd64.tar.gz"
      sha256 "c9cdc38e12fd83dbe9780da285eb23da3cc7dad1a9154f827bdb0d8a58efb19f"

      def install
        bin.install "cloudexec"
      end
    end
  end

  def caveats
    <<~EOS
      CloudExec can optionally use the 1Password CLI for secure credential management.
      To use this feature, you need to have the 1Password CLI installed.

      To install the 1Password CLI, run:
        brew install --cask 1password-cli

      For more information on using 1Password CLI with CloudExec, visit:
      https://github.com/crytic/cloudexec#configure-credentials
    EOS
  end

  test do
    system "#{bin}/cloudexec version"
  end
end
