# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Cloudfuzz < Formula
  desc ""
  homepage "https://github.com/trailofbits/cloudfuzz"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.3/cloudfuzz-0.0.3-darwin-amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "3e23a65f8e9f7558cdba913b9049b89f8094ee032ada76c72185818123fde6fb"

      def install
        bin.install "cloudfuzz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.3/cloudfuzz-0.0.3-darwin-arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "96be7e8fbf3a1bd2612614a34851e8f1b9ea9955d8a078ff4f9e306824701387"

      def install
        bin.install "cloudfuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.3/cloudfuzz-0.0.3-linux-arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "a5d307458cc3588195eda452f62a5982578e37940c0c8ce2039230ac151cada9"

      def install
        bin.install "cloudfuzz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.3/cloudfuzz-0.0.3-linux-amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "c237127daf93f14993bcb25877ffba78679ceb0015896f74cdb8d9c49a0a957a"

      def install
        bin.install "cloudfuzz"
      end
    end
  end

  def caveats
    <<~EOS
      CloudFuzz can optionally use the 1Password CLI for secure credential management.
      To use this feature, you need to have the 1Password CLI installed.

      To install the 1Password CLI, run:
        brew install --cask 1password-cli

      For more information on using 1Password CLI with CloudFuzz, visit:
      https://github.com/trailofbits/cloudfuzz#configure-credentials
    EOS
  end

  test do
    system "#{bin}/cloudfuzz version"
  end
end
