# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudexec < Formula
  desc ""
  homepage "https://github.com/crytic/cloudexec"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crytic/cloudexec/releases/download/v0.2.0/cloudexec-0.2.0-darwin-arm64.tar.gz"
      sha256 "c23dc69c7764570f4dda47e306d3814abdfd511330e2f9557c35d1058c1e8b62"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.2.0/cloudexec-0.2.0-darwin-amd64.tar.gz"
      sha256 "0a4874beb13784acb2bff9ee741444297d4ca21ad56fe03b479af78b382c5966"

      def install
        bin.install "cloudexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.2.0/cloudexec-0.2.0-linux-amd64.tar.gz"
      sha256 "038f9fb4fb8d4c9273d84672e40061d9545d796a05d90495dd62e2572d1a9d96"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crytic/cloudexec/releases/download/v0.2.0/cloudexec-0.2.0-linux-arm64.tar.gz"
      sha256 "8d6f8b555544a16051c380d5fd19b41b5a202ae6ecbf4db7c195567453321a92"

      def install
        bin.install "cloudexec"
      end
    end
  end

  def caveats
    <<~EOS
      CloudExec can optionally use the 1Password CLI for secure credential management.
      To use this feature, you need to have the 1Password CLI installed.

      To install the 1Password CLI, run:
        brew install --cask 1password-cli

      For more information on using 1Password CLI with CloudExec, visit:
      https://github.com/crytic/cloudexec#configure-credentials
    EOS
  end

  test do
    system "#{bin}/cloudexec version"
  end
end
