# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Cloudfuzz < Formula
  desc ""
  homepage "https://github.com/trailofbits/cloudfuzz"
  version "0.0.9-SNAPSHOT-9075f8d"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.9/cloudfuzz_darwin_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "9a4660bf8d7912eae6de27b773f7e5ee5becf1f6b40b46ba8493195d7988625a"

      def install
        bin.install "cloudfuzz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.9/cloudfuzz_darwin_x86_64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "c8ef7e0c78594a8c26683d6a1c827548816c0e0c3fb80848d6ce887410b5b268"

      def install
        bin.install "cloudfuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.9/cloudfuzz_linux_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "92a105ec33845f4c83075c8f7033ecde3f30c50d20ca2b4562b8629b42f5e516"

      def install
        bin.install "cloudfuzz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/trailofbits/cloudfuzz/releases/download/v0.0.9/cloudfuzz_linux_x86_64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "7ce6cd30fbbb60756d790cda9827f9fc163ea5e4ed94f0b13b7e0bcf87d931e2"

      def install
        bin.install "cloudfuzz"
      end
    end
  end
end
