# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudexec < Formula
  desc ""
  homepage "https://github.com/crytic/cloudexec"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.2/cloudexec-0.1.2-darwin-arm64.tar.gz"
      sha256 "777f13a775db3b9ce5f3b7e4cc7d17e77a653784c0f17750ae7b9e5fae426b2d"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.2/cloudexec-0.1.2-darwin-amd64.tar.gz"
      sha256 "f359f953148b4d6eac19673aa3fd159381f9ee8b9965899a2a29fd3004e2108d"

      def install
        bin.install "cloudexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.2/cloudexec-0.1.2-linux-arm64.tar.gz"
      sha256 "c006ac931ce2cdcd5934450c44a41acebdba556ffb2a8eca50ee50795d11c0ca"

      def install
        bin.install "cloudexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/crytic/cloudexec/releases/download/v0.1.2/cloudexec-0.1.2-linux-amd64.tar.gz"
      sha256 "442bbb352ae3f11b8de035b3d4e72c4453242bfcbd86fc78cb3065d86d17ed73"

      def install
        bin.install "cloudexec"
      end
    end
  end

  def caveats
    <<~EOS
      CloudExec can optionally use the 1Password CLI for secure credential management.
      To use this feature, you need to have the 1Password CLI installed.

      To install the 1Password CLI, run:
        brew install --cask 1password-cli

      For more information on using 1Password CLI with CloudExec, visit:
      https://github.com/crytic/cloudexec#configure-credentials
    EOS
  end

  test do
    system "#{bin}/cloudexec version"
  end
end
